apiVersion: v1
kind: Service
metadata:
  name: scenario-1-server-service
spec:
  type: NodePort
  selector:
    app: scenario-1-server
  ports:
  - port: 4242
    targetPort: 4242
    nodePort: 30042
    name: scenario-1-nodeport

